import { defineConfig } from 'tsup'

export default defineConfig({
  entry: ['src/entrypoints/main.ts'],
  format: ['cjs'], // Only build CJS, ESM is handled by tsc
  dts: false, // Types are generated by tsc
  sourcemap: true,
  clean: false, // Don't clean, tsc output is already there
  outDir: 'build/entrypoints',
  outExtension({ format }) {
    return {
      js: '.cjs',
    }
  },
  external: [
    'graphql', // Peer dependency, don't bundle
  ],
  // Bundle everything else for a single CJS file
  splitting: false,
  treeshake: true,
  minify: false,
})
