export const $ = {
  $$Schema: `$$Schema`,
  $$Scalar: `$$Scalar`,
  $$SelectionSets: `$$SelectionSets`,
  $$ArgumentsMap: `$$ArgumentsMap`,
  $$Tada: `$$Tada`,
  $$MethodsSelect: `$$MethodsSelect`,
  $$MethodsDocument: `$$MethodsDocument`,
  $$MethodsRoot: `$$MethodsRoot`,
  $$Data: `$$Data`,
  $$SchemaDrivenDataMap: `$$SchemaDrivenDataMap`,
  $$Utilities: `$$Utilities`,
  Schema: `Schema`,
  CustomScalars: `CustomScalars`,
  StandardScalar: `StandardScalar`,
}
