/**
 * ====================================================================================
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * ====================================================================================
 *
 * Generated by: Graffle Code Generator
 * Source: src/generator/generators/ArgumentsMap.ts
 *
 * @module ArgumentsMap
 *
 * ArgumentsMap is a type-level structure that mirrors your GraphQL schema's argument structure for type-safe variable inference.
 *
 * @description
 *
 * ArgumentsMap provides a complete type-level representation of all arguments in your GraphQL schema. It enables the Static Document Builder to infer variable types and requirements from your selection sets when you use `$var` placeholders.
 *
 * This module is generated from your GraphQL schema and creates TypeScript interfaces that encode:
 *
 * - Which fields accept arguments
 * - The types and nullability of those arguments
 * - Nested argument structures in complex queries
 * - Input object types used in arguments
 *
 * The ArgumentsMap works in conjunction with the variable inference system to provide compile-time validation of your GraphQL variables without requiring manual type annotations.
 *
 * @remarks
 *
 * ArgumentsMap follows the Schema-Driven Data Map (SDDM) pattern used throughout Graffle's generated code. This pattern uses specific property names with precise meanings:
 *
 * - `operations`: Root types (query, mutation, subscription) that can be directly queried
 * - `directives`: Directive definitions with their arguments
 * - `types`: All types in the schema that have fields with arguments
 * - `f`: Fields map - contains all fields for a given type
 * - `a`: Arguments - direct arguments on a specific field
 * - `ad`: Arguments descendant - reference to a type that has fields with arguments
 * - `nt`: Named type - the GraphQL type name as a string literal
 * - `it`: Inline type - tuple encoding nullability: `[0]` for nullable, `[1]` for required, `[0, [1]]` for list types
 * - `$t`: TypeScript type - the fully resolved TypeScript type for the argument
 *
 * The `ad` property is particularly important: it enables type traversal through fields that don't have direct arguments but return types that do have fields with arguments. This allows the type system to properly track argument requirements across nested selections.
 *
 * @example Basic Field Arguments
 *
 * A simple field with optional scalar arguments:
 *
 * ```typescript
 * export interface Query extends $$Utilities.SchemaDrivenDataMap.OutputObject {
 *   readonly f: {
 *     readonly userById: {
 *       readonly a: {
 *         readonly id: {
 *           readonly nt: 'ID'
 *           readonly it: readonly [0]
 *           readonly $t: string | undefined
 *         }
 *       }
 *     }
 *   }
 * }
 * ```
 *
 * @example Required Arguments
 *
 * A field with a required argument (non-null in GraphQL schema):
 *
 * ```typescript
 * readonly stringWithRequiredArg: {
 *   readonly a: {
 *     readonly string: {
 *       readonly nt: 'String'
 *       readonly it: readonly [1]
 *       readonly $t: string
 *     }
 *   }
 * }
 * ```
 *
 * @example List Arguments
 *
 * Arguments that accept arrays:
 *
 * ```typescript
 * readonly stringWithListArgRequired: {
 *   readonly a: {
 *     readonly ints: {
 *       readonly nt: 'Int'
 *       readonly it: readonly [1, [1]]
 *       readonly $t: readonly number[]
 *     }
 *   }
 * }
 * ```
 *
 * @example Nested Arguments with Descendant
 *
 * A field that doesn't have direct arguments but returns a type with fields that do:
 *
 * ```typescript
 * readonly objectNestedWithArgs: {
 *   readonly ad: ObjectNestedWithArgs
 * }
 * ```
 *
 * Where `ObjectNestedWithArgs` is defined elsewhere:
 *
 * ```typescript
 * export interface ObjectNestedWithArgs
 *   extends $$Utilities.SchemaDrivenDataMap.OutputObject
 * {
 *   readonly f: {
 *     readonly object: {
 *       readonly a: {
 *         readonly int: {
 *           readonly nt: 'Int'
 *           readonly it: readonly [0]
 *           readonly $t: number | undefined
 *         }
 *       }
 *     }
 *   }
 * }
 * ```
 *
 * @example Input Object Arguments
 *
 * Arguments that accept input objects:
 *
 * ```typescript
 * readonly stringWithArgInputObjectRequired: {
 *   readonly a: {
 *     readonly input: {
 *       readonly nt: 'InputObject'
 *       readonly it: readonly [1]
 *       readonly $t: TypeInputsIndex.InputObject
 *     }
 *   }
 * }
 * ```
 *
 * @see {@link https://graffle.js.org | Graffle Documentation}
 * @see {@link https://graffle.js.org/guides/document-builder | Static Document Builder Guide}
 */

import type * as $$Utilities from '#graffle/utilities-for-generated'
import type * as TypeInputsIndex from './type-inputs-index.js'

//
//
//
//
//
//
// ==================================================================================================
//                                            InputObject
// ==================================================================================================
//
//
//
//
//
//

export interface InputObject extends $$Utilities.SchemaDrivenDataMap.InputObject {
  readonly _tag: 'inputObject'
  readonly name: 'InputObject'
  readonly fields: {
    readonly abcEnum: {
      readonly _tag: 'argumentOrInputField'
      readonly namedType: 'ABCEnum'
      readonly inlineType: readonly [0]
      readonly $type: TypeInputsIndex.ABCEnum | null | undefined
    }
    readonly date: {
      readonly _tag: 'argumentOrInputField'
      readonly namedType: 'Date'
      readonly inlineType: readonly [0]
      readonly $type: TypeInputsIndex.Date | null | undefined
    }
    readonly dateRequired: {
      readonly _tag: 'argumentOrInputField'
      readonly namedType: 'Date'
      readonly inlineType: readonly [1]
      readonly $type: TypeInputsIndex.Date
    }
    readonly id: {
      readonly _tag: 'argumentOrInputField'
      readonly namedType: 'ID'
      readonly inlineType: readonly [0]
      readonly $type: TypeInputsIndex.ID | null | undefined
    }
    readonly idRequired: {
      readonly _tag: 'argumentOrInputField'
      readonly namedType: 'ID'
      readonly inlineType: readonly [1]
      readonly $type: TypeInputsIndex.ID
    }
  }
}

export interface InputObjectCircular extends $$Utilities.SchemaDrivenDataMap.InputObject {
  readonly _tag: 'inputObject'
  readonly name: 'InputObjectCircular'
  readonly fields: {
    readonly circular: {
      readonly _tag: 'argumentOrInputField'
      readonly namedType: 'InputObjectCircular'
      readonly inlineType: readonly [0]
      readonly $type: TypeInputsIndex.InputObjectCircular | null | undefined
    }
    readonly date: {
      readonly _tag: 'argumentOrInputField'
      readonly namedType: 'Date'
      readonly inlineType: readonly [0]
      readonly $type: TypeInputsIndex.Date | null | undefined
    }
  }
}

export interface InputObjectEnum extends $$Utilities.SchemaDrivenDataMap.InputObject {
  readonly _tag: 'inputObject'
  readonly name: 'InputObjectEnum'
  readonly fields: {
    readonly abcEnum: {
      readonly _tag: 'argumentOrInputField'
      readonly namedType: 'ABCEnum'
      readonly inlineType: readonly [0]
      readonly $type: TypeInputsIndex.ABCEnum | null | undefined
    }
  }
}

export interface InputObjectNested extends $$Utilities.SchemaDrivenDataMap.InputObject {
  readonly _tag: 'inputObject'
  readonly name: 'InputObjectNested'
  readonly fields: {
    readonly InputObject: {
      readonly _tag: 'argumentOrInputField'
      readonly namedType: 'InputObject'
      readonly inlineType: readonly [0]
      readonly $type: TypeInputsIndex.InputObject | null | undefined
    }
  }
}

export interface InputObjectNestedNonNull extends $$Utilities.SchemaDrivenDataMap.InputObject {
  readonly _tag: 'inputObject'
  readonly name: 'InputObjectNestedNonNull'
  readonly fields: {
    readonly InputObject: {
      readonly _tag: 'argumentOrInputField'
      readonly namedType: 'InputObject'
      readonly inlineType: readonly [1]
      readonly $type: TypeInputsIndex.InputObject
    }
  }
}

//
//
//
//
//
//
// ==================================================================================================
//                                            OutputObject
// ==================================================================================================
//
//
//
//
//
//

export interface ObjectNestedWithArgs extends $$Utilities.SchemaDrivenDataMap.OutputObject {
  readonly _tag: 'outputObject'
  readonly fields: {
    readonly id: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly filter: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'ID'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.ID | null | undefined
        }
      }
    }
    readonly object: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly boolean: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Boolean'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.Boolean | null | undefined
        }
        readonly float: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Float'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.Float | null | undefined
        }
        readonly int: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Int'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.Int | null | undefined
        }
        readonly string: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'String'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.String | null | undefined
        }
      }
    }
  }
}

//
//
//
//
//
//
// ==================================================================================================
//                                             Interface
// ==================================================================================================
//
//
//
//
//
//

// No Interface types with arguments in your schema.

//
//
//
//
//
//
// ==================================================================================================
//                                               Union
// ==================================================================================================
//
//
//
//
//
//

// No Union types with arguments in your schema.

//
//
//
//
//
//
// ==================================================================================================
//                                                Root
// ==================================================================================================
//
//
//
//
//
//

export interface Query extends $$Utilities.SchemaDrivenDataMap.OutputObject {
  readonly _tag: 'outputObject'
  readonly fields: {
    readonly InputObjectNested: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly input: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'InputObjectNested'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.InputObjectNested | null | undefined
        }
      }
    }
    readonly InputObjectNestedNonNull: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly input: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'InputObjectNestedNonNull'
          readonly inlineType: readonly [1]
          readonly $type: TypeInputsIndex.InputObjectNestedNonNull
        }
      }
    }
    readonly argInputObjectCircular: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly input: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'InputObjectCircular'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.InputObjectCircular | null | undefined
        }
      }
    }
    readonly dateArg: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly date: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Date'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.Date | null | undefined
        }
      }
    }
    readonly dateArgInputObject: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly input: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'InputObject'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.InputObject | null | undefined
        }
      }
    }
    readonly dateArgList: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly date: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Date'
          readonly inlineType: readonly [0, [1]]
          readonly $type: readonly TypeInputsIndex.Date[] | null | undefined
        }
      }
    }
    readonly dateArgNonNull: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly date: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Date'
          readonly inlineType: readonly [1]
          readonly $type: TypeInputsIndex.Date
        }
      }
    }
    readonly dateArgNonNullList: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly date: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Date'
          readonly inlineType: readonly [1, [0]]
          readonly $type: readonly TypeInputsIndex.Date[]
        }
      }
    }
    readonly dateArgNonNullListNonNull: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly date: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Date'
          readonly inlineType: readonly [1, [1]]
          readonly $type: readonly TypeInputsIndex.Date[]
        }
      }
    }
    readonly error: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly case: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'String'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.String | null | undefined
        }
      }
    }
    readonly interfaceHierarchyChildA: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly type: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'ChildAInterfaceHierarchyMember'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.ChildAInterfaceHierarchyMember | null | undefined
        }
      }
    }
    readonly interfaceHierarchyChildB: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly type: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'ChildBInterfaceHierarchyMember'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.ChildBInterfaceHierarchyMember | null | undefined
        }
      }
    }
    readonly interfaceHierarchyGrandparents: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly type: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'GrandparentInterfaceHierarchyMember'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.GrandparentInterfaceHierarchyMember | null | undefined
        }
      }
    }
    readonly interfaceHierarchyParents: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly type: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'ParentInterfaceHierarchyMember'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.ParentInterfaceHierarchyMember | null | undefined
        }
      }
    }
    readonly interfaceWithArgs: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly id: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'ID'
          readonly inlineType: readonly [1]
          readonly $type: TypeInputsIndex.ID
        }
      }
    }
    readonly objectNestedWithArgs: {
      readonly _tag: 'outputField'
      readonly argumentsDescendant: ObjectNestedWithArgs
    }
    readonly objectWithArgs: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly boolean: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Boolean'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.Boolean | null | undefined
        }
        readonly float: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Float'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.Float | null | undefined
        }
        readonly id: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'ID'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.ID | null | undefined
        }
        readonly int: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Int'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.Int | null | undefined
        }
        readonly string: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'String'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.String | null | undefined
        }
      }
    }
    readonly result: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly case: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Case'
          readonly inlineType: readonly [1]
          readonly $type: TypeInputsIndex.Case
        }
      }
    }
    readonly resultNonNull: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly case: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Case'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.Case | null | undefined
        }
      }
    }
    readonly stringWithArgEnum: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly ABCEnum: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'ABCEnum'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.ABCEnum | null | undefined
        }
      }
    }
    readonly stringWithArgInputObject: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly input: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'InputObject'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.InputObject | null | undefined
        }
      }
    }
    readonly stringWithArgInputObjectEnum: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly input: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'InputObjectEnum'
          readonly inlineType: readonly [1]
          readonly $type: TypeInputsIndex.InputObjectEnum
        }
      }
    }
    readonly stringWithArgInputObjectRequired: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly input: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'InputObject'
          readonly inlineType: readonly [1]
          readonly $type: TypeInputsIndex.InputObject
        }
      }
    }
    readonly stringWithArgs: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly boolean: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Boolean'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.Boolean | null | undefined
        }
        readonly float: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Float'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.Float | null | undefined
        }
        readonly id: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'ID'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.ID | null | undefined
        }
        readonly int: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Int'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.Int | null | undefined
        }
        readonly string: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'String'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.String | null | undefined
        }
      }
    }
    readonly stringWithListArg: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly ints: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Int'
          readonly inlineType: readonly [0, [0]]
          readonly $type: readonly TypeInputsIndex.Int[] | null | undefined
        }
      }
    }
    readonly stringWithListArgRequired: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly ints: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'Int'
          readonly inlineType: readonly [1, [1]]
          readonly $type: readonly TypeInputsIndex.Int[]
        }
      }
    }
    readonly stringWithRequiredArg: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly string: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'String'
          readonly inlineType: readonly [1]
          readonly $type: TypeInputsIndex.String
        }
      }
    }
    readonly unionFooBarWithArgs: {
      readonly _tag: 'outputField'
      readonly arguments: {
        readonly id: {
          readonly _tag: 'argumentOrInputField'
          readonly namedType: 'ID'
          readonly inlineType: readonly [0]
          readonly $type: TypeInputsIndex.ID | null | undefined
        }
      }
    }
  }
}

//
//
//
//
//
//
// ==================================================================================================
//                                                Root
// ==================================================================================================
//
//
//
//
//
//

export interface Mutation extends $$Utilities.SchemaDrivenDataMap.OutputObject {
  readonly _tag: 'outputObject'
  readonly fields: {}
}

//
//
//
//
//
//
// ==================================================================================================
//                                               Index
// ==================================================================================================
//
//
//
//
//
//

export interface ArgumentsMap {
  operations: {
    query: Query
    mutation: Mutation
  }
  directives: {}
  inputTypes: {
    InputObject: InputObject
    InputObjectCircular: InputObjectCircular
    InputObjectEnum: InputObjectEnum
    InputObjectNested: InputObjectNested
    InputObjectNestedNonNull: InputObjectNestedNonNull
  }
  outputTypes: {
    ObjectNestedWithArgs: ObjectNestedWithArgs
    Query: Query
    Mutation: Mutation
  }
}
