export { type Infer as InferOperationVariablesFromSelectionSet } from './InferOperationVariablesFromSelectionSet/__.js'
export * from './InferResult/__.js'
export * from './requestMethods/document.js'
export * from './requestMethods/requestMethods.js'
export * from './Select/__.js'
export * from './SelectGraphQLMapper/_namespace.js'
export { createStaticRootType } from './staticBuilder.js'
export { $var, type VariableMarker } from './variable.js'
