export { DocumentBuilder } from '../../../extensions/DocumentBuilder/DocumentBuilder.js'
export { createStaticRootType } from '../../../extensions/DocumentBuilder/staticBuilder.js'
export { defaults as staticBuilderDefaults } from '../../../extensions/DocumentBuilder/staticBuilderDefaults.js'
export { Var } from '../../../extensions/DocumentBuilder/var/$.js'
export { $var } from '../../../extensions/DocumentBuilder/var/$$.js'
