export { DocumentBuilder } from '../../../extensions/DocumentBuilder/DocumentBuilder.js'
export { createStaticRootType, type Config, type StaticDocumentBuilder } from '../../../extensions/DocumentBuilder/staticBuilder.js'
export { defaults as staticBuilderDefaults } from '../../../extensions/DocumentBuilder/staticBuilderDefaults.js'
export { $ } from '../../../extensions/DocumentBuilder/var/$$.js'
export { Var } from '../../../extensions/DocumentBuilder/var/$.js'
