// @vitest-environment node

// WARNING:
// This test is generated by scripts/generate-example-derivatives/generate.ts
// Do not modify this file directly.

import { expect, test } from 'vitest'
import { runExampleForTest } from '../../../scripts/generate-examples-derivatives/helpers.js'

test(`document-builder_directive`, async () => {
  const exampleResult = await runExampleForTest(`./55_document-builder/document-builder_directive.ts`)
  // Examples should output their data results.
  const exampleResultMaybeEncoded = exampleResult
  // If ever outputs vary by Node version, you can use this to snapshot by Node version.
  // const nodeMajor = process.version.match(/v(\d+)/)?.[1] ?? `unknown`
  await expect(exampleResultMaybeEncoded).toMatchFileSnapshot(
    `../../__outputs__/55_document-builder/document-builder_directive.output.test.txt`,
  )
})
