export { InferResult } from './InferResult/$.js'
export * as Static from './rootType.js'
export { Select } from './Select/$.js'
export { ToGraphQLDocument } from './ToGraphQLDocument/$.js'
export { Var } from './var/$.js'
