import type { Ts } from '@wollybeard/kit'

export { createConstructorWithContext } from '#src/client/client.js'
export {
  type ConfigGetOutputError,
  type HandleOutput,
  type HandleOutputDocumentBuilderRootField,
} from '#src/client/handle.js'
export { type Context } from '#src/context/context.js'
export * from '#src/context/context.js'
export { contextEmpty } from '#src/context/ContextEmpty.js'
export { addAndApplyMany } from '#src/context/fragments/extensions/fragment.js'
export { Docpar } from '#src/docpar/$.js'
export { type SchemaDrivenDataMap } from '#src/docpar/core/sddm/SchemaDrivenDataMap.js'
export { type DocumentRunner } from '#src/extensions/DocumentBuilder/methods-instance/document.js'
export { type DocumentRunner as DocumentRunnerDeferred } from '#src/extensions/DocumentBuilder/methods-instance/requestMethods.js'
export { GraphqlKit } from '#src/lib/graphql-kit/_.js'
export { type gql } from '#src/static/gql.js'
export { ContextFragments } from '#src/types/ContextFragment.js'
export { type GlobalRegistry } from '#src/types/GlobalRegistry/GlobalRegistry.js'
export * from '#src/types/Schema/StandardTypes/scalar.js'
export * from '#src/utils.js'
export { Ts } from '@wollybeard/kit'
export { Kind } from '@wollybeard/kit/fn'
export { pipe } from '@wollybeard/kit/fn'
// todo
// export type { NoExcess, NoExcessNonEmpty } from '@wollybeard/kit/obj'
export type { AssertExtendsObject } from '@wollybeard/kit/ts'
export type { Simplify } from 'type-fest'
export { Configuration } from '../context/fragments/configuration/$.js'
export { Extensions } from '../context/fragments/extensions/$.js'
export { Scalars } from '../context/fragments/scalars/$.js'
export { Transports } from '../context/fragments/transports/$.js'
export * from '../types/RequestResult/$.js'
export { Schema } from '../types/Schema/$.js'
export * from './kit.js'
